type GreetingFn = (firstName: string, tutorName: string) => string;

const greetings: Record<string, GreetingFn[]> = {
  "Self Introduction": [
    (f, t) => `Hey ${f}! This is ${t}. So, tell me — if you had to describe yourself in three words, what would they be?`,
    (f, t) => `Hi ${f}, ${t} here! Let's dive right in. Start with your name and where you're from, and we'll build from there.`,
    (f, t) => `Hello ${f}! I'm ${t}. Imagine you're meeting someone at a party for the first time — how would you introduce yourself?`,
    (f, t) => `Hey ${f}! ${t} speaking. You've got 30 seconds to make a great first impression — go ahead, introduce yourself!`,
    (f, t) => `Hi ${f}! It's ${t}. Let's say you just started a new job. How would you introduce yourself to your new team?`,
    (f, t) => `Hello ${f}, ${t} here. What's one thing about yourself that most people find surprising when they first meet you?`,
    (f, t) => `Hey ${f}! This is ${t}. Besides your name and job, what do you think makes you… you?`,
    (f, t) => `Hi ${f}! ${t} here. Let's practice introductions. Start anywhere — name, hometown, hobbies — whatever feels natural.`,
    (f, t) => `Hello ${f}! I'm ${t}. Picture this: you're at an international conference. Give me your best 30-second intro!`,
    (f, t) => `Hey ${f}, it's ${t}! What's something you're really passionate about that you love telling new people about?`,
    (f, t) => `Hi ${f}! ${t} calling. Let's get started — tell me a little about your background and what you do.`,
    (f, t) => `Hello ${f}! This is ${t}. If someone asked you to describe your life in one sentence, what would you say?`,
    (f, t) => `Hey ${f}! ${t} here. What's a fun fact about yourself you always bring up when meeting new people?`,
    (f, t) => `Hi ${f}, it's ${t}. Let's practice. Walk me through your day — where do you live, what do you do, what are you into?`,
    (f, t) => `Hello ${f}! I'm ${t}. If you were writing your own bio for a website, how would it start?`,
    (f, t) => `Hey ${f}! ${t} speaking. What's the most interesting thing about where you grew up?`,
    (f, t) => `Hi ${f}! This is ${t}. Let's say we just met at a café. What would you tell me about yourself first?`,
    (f, t) => `Hello ${f}, ${t} here! What are two or three things you'd want a stranger to know about you right away?`,
    (f, t) => `Hey ${f}! It's ${t}. Everyone has a story — so what's yours? Where did you grow up, and how did you end up where you are now?`,
    (f, t) => `Hi ${f}! ${t} calling. Imagine you're on a first date — how would you describe yourself without talking about your job?`,
  ],

  "Daily Conversation": [
    (f, t) => `Hey ${f}! It's ${t}. How's your day going so far?`,
    (f, t) => `Hi ${f}, ${t} here! What's been the highlight of your week?`,
    (f, t) => `Hello ${f}! I'm ${t}. Did anything interesting happen to you today?`,
    (f, t) => `Hey ${f}! ${t} speaking. What are your plans for the weekend?`,
    (f, t) => `Hi ${f}! This is ${t}. What's the weather like where you are right now?`,
    (f, t) => `Hello ${f}, ${t} here. Is there anything you've been looking forward to lately?`,
    (f, t) => `Hey ${f}! It's ${t}. Morning or night person — which one are you, and why?`,
    (f, t) => `Hi ${f}! ${t} calling. What's something small that made you smile recently?`,
    (f, t) => `Hello ${f}! This is ${t}. How do you usually unwind after a long day?`,
    (f, t) => `Hey ${f}, ${t} here! Have you tried anything new lately — food, a hobby, a place?`,
    (f, t) => `Hi ${f}! I'm ${t}. What's your morning routine like these days?`,
    (f, t) => `Hello ${f}! ${t} speaking. What's been keeping you busy lately?`,
    (f, t) => `Hey ${f}! It's ${t}. If you had a free afternoon with nothing to do, how would you spend it?`,
    (f, t) => `Hi ${f}, ${t} calling! What's a random topic you've been thinking about or curious about recently?`,
    (f, t) => `Hello ${f}! This is ${t}. What's one thing you're really looking forward to this month?`,
    (f, t) => `Hey ${f}! ${t} here. Tell me about the last time you genuinely laughed — what happened?`,
    (f, t) => `Hi ${f}! I'm ${t}. Do you prefer busy days or slow days, and what does a perfect day look like for you?`,
    (f, t) => `Hello ${f}, ${t} speaking! What's something you've been meaning to do but keep putting off?`,
    (f, t) => `Hey ${f}! It's ${t}. If you could go anywhere this weekend with no limits, where would you go?`,
    (f, t) => `Hi ${f}! ${t} here. What's a habit you've picked up recently that you're actually proud of?`,
  ],

  "Business English": [
    (f, t) => `Good day ${f}! I'm ${t}. Let's say you're in your first week at a new company — how would you introduce yourself to a colleague?`,
    (f, t) => `Hello ${f}! ${t} here. Imagine you need to send a professional email to a client you've never met. How would you open it?`,
    (f, t) => `Hi ${f}! This is ${t}. Let's practice meetings. How do you usually start a team meeting in English?`,
    (f, t) => `Good morning ${f}! ${t} speaking. You need to present a project update to your boss — walk me through how you'd open that presentation.`,
    (f, t) => `Hello ${f}, ${t} here. What's a business situation in English that you find most challenging?`,
    (f, t) => `Hi ${f}! I'm ${t}. Let's practice small talk before a big meeting. What do you usually say to break the ice?`,
    (f, t) => `Good day ${f}! ${t} calling. Imagine you're networking at a business event. How do you approach someone you'd like to connect with?`,
    (f, t) => `Hello ${f}! This is ${t}. You've just joined a video call and there are five minutes before it starts. What do you say to fill the silence professionally?`,
    (f, t) => `Hi ${f}, ${t} here! Let's work on negotiation phrases. How would you politely push back on a proposal you disagree with?`,
    (f, t) => `Good morning ${f}! I'm ${t}. Walk me through how you'd wrap up a business meeting and confirm next steps.`,
    (f, t) => `Hello ${f}! ${t} speaking. What's a recent work situation where you had to communicate in English? Tell me about it.`,
    (f, t) => `Hi ${f}! This is ${t}. Let's practice. You need to ask your foreign colleague for a deadline extension — how would you phrase that?`,
    (f, t) => `Good day ${f}, ${t} here! How would you politely decline a meeting invitation in a professional email?`,
    (f, t) => `Hello ${f}! I'm ${t}. Imagine you're giving feedback to a colleague in English. How do you start a constructive feedback conversation?`,
    (f, t) => `Hi ${f}! ${t} calling. Let's say a client is upset about a delay. How would you handle that conversation in English?`,
    (f, t) => `Good morning ${f}! This is ${t}. What business English phrases do you wish you were more confident using?`,
    (f, t) => `Hello ${f}, ${t} here. You're leading a brainstorming session — how do you kick it off and invite people to share ideas?`,
    (f, t) => `Hi ${f}! I'm ${t}. Let's practice job interviews. How would you answer, "Tell me about yourself," in a professional context?`,
    (f, t) => `Good day ${f}! ${t} speaking. You've received a job offer and want to negotiate the salary — how would you start that conversation?`,
    (f, t) => `Hello ${f}! This is ${t}. Walk me through how you'd give a status update on a project that's slightly behind schedule.`,
  ],

  "Travel": [
    (f, t) => `Hi ${f}! It's ${t}. If you could book a flight anywhere in the world right now, where would you go?`,
    (f, t) => `Hey ${f}, ${t} here! What's the most memorable trip you've ever taken?`,
    (f, t) => `Hello ${f}! This is ${t}. Are you more of a beach person or a mountain person when it comes to travel?`,
    (f, t) => `Hi ${f}! I'm ${t}. What's a destination that's been on your bucket list for a long time?`,
    (f, t) => `Hey ${f}! ${t} speaking. What do you think makes a trip truly unforgettable?`,
    (f, t) => `Hello ${f}, ${t} here! Do you prefer traveling solo or with others, and why?`,
    (f, t) => `Hi ${f}! It's ${t}. Tell me about a place that completely surprised you — in a good way!`,
    (f, t) => `Hey ${f}! This is ${t}. What's one travel experience that changed the way you see the world?`,
    (f, t) => `Hello ${f}! ${t} calling. What kind of traveler are you — planner or go-with-the-flow?`,
    (f, t) => `Hi ${f}, ${t} here! If you had two weeks and no budget limits, what would your dream trip look like?`,
    (f, t) => `Hey ${f}! I'm ${t}. What's the best local food you've ever discovered while traveling?`,
    (f, t) => `Hello ${f}! ${t} speaking. Have you ever had a travel mishap that turned into a funny story?`,
    (f, t) => `Hi ${f}! This is ${t}. What's something you always pack no matter where you're going?`,
    (f, t) => `Hey ${f}, ${t} here! Is there a country or city you've always wanted to visit but haven't made it to yet?`,
    (f, t) => `Hello ${f}! It's ${t}. What's your favorite thing about exploring a new city for the first time?`,
    (f, t) => `Hi ${f}! I'm ${t}. If you could live in another country for a year, which one would you choose?`,
    (f, t) => `Hey ${f}! ${t} calling. What travel advice would you give someone visiting Korea for the first time?`,
    (f, t) => `Hello ${f}! This is ${t}. What's the most beautiful thing you've ever seen while traveling?`,
    (f, t) => `Hi ${f}, ${t} here! Do you prefer short weekend trips or long vacations? What's your ideal travel length?`,
    (f, t) => `Hey ${f}! I'm ${t}. Have you ever traveled somewhere alone? How was that experience?`,
  ],

  "Health & Fitness": [
    (f, t) => `Hey ${f}! It's ${t}. Do you have any kind of workout routine going on these days?`,
    (f, t) => `Hi ${f}, ${t} here! What's your go-to way to stay active — gym, running, sports, something else?`,
    (f, t) => `Hello ${f}! This is ${t}. What's been the biggest challenge for you when it comes to staying healthy?`,
    (f, t) => `Hey ${f}! I'm ${t}. Have you picked up any new health habits recently that you're actually sticking to?`,
    (f, t) => `Hi ${f}! ${t} speaking. How do you find the motivation to exercise when you really don't feel like it?`,
    (f, t) => `Hello ${f}, ${t} calling! What does a healthy week look like for you — workouts, food, sleep?`,
    (f, t) => `Hey ${f}! This is ${t}. Are you more into cardio or strength training — or something completely different?`,
    (f, t) => `Hi ${f}! I'm ${t}. What's the one health or fitness goal you're working on right now?`,
    (f, t) => `Hello ${f}! ${t} here. How important is sleep to you, and do you think you get enough of it?`,
    (f, t) => `Hey ${f}, ${t} speaking! Have you ever tried a fitness trend that everyone was talking about? Did it work for you?`,
    (f, t) => `Hi ${f}! It's ${t}. Do you pay attention to what you eat, or do you follow any particular diet?`,
    (f, t) => `Hello ${f}! This is ${t}. What's the most intense workout or physical challenge you've ever done?`,
    (f, t) => `Hey ${f}! I'm ${t}. How do you deal with stress — do you exercise it off or do something else?`,
    (f, t) => `Hi ${f}, ${t} here! What's one small change you've made to your lifestyle that had a surprisingly big impact?`,
    (f, t) => `Hello ${f}! ${t} calling. Do you think mental health and physical health are connected? How so?`,
    (f, t) => `Hey ${f}! This is ${t}. What's your relationship with rest days — do you take them guilt-free or do you struggle?`,
    (f, t) => `Hi ${f}! I'm ${t}. What's a sport or physical activity you've always wanted to try but never have?`,
    (f, t) => `Hello ${f}, ${t} speaking! How do you stay active when you're really busy — any tips?`,
    (f, t) => `Hey ${f}! It's ${t}. Have you ever trained for something specific, like a race or a competition? Tell me about it.`,
    (f, t) => `Hi ${f}! This is ${t}. What does "feeling healthy" mean to you personally — what does that look and feel like?`,
  ],

  "Food & Cooking": [
    (f, t) => `Hi ${f}! It's ${t}. What's something delicious you've eaten recently that you'd highly recommend?`,
    (f, t) => `Hey ${f}, ${t} here! Do you enjoy cooking, or are you more of a "let's order in" kind of person?`,
    (f, t) => `Hello ${f}! This is ${t}. If you had to cook dinner for a guest tonight, what would you make?`,
    (f, t) => `Hi ${f}! I'm ${t}. What's a dish from Korean food that you think people around the world should know about?`,
    (f, t) => `Hey ${f}! ${t} speaking. Is there a food you absolutely can't stand — and why?`,
    (f, t) => `Hello ${f}, ${t} here! What's the most adventurous food you've ever tried?`,
    (f, t) => `Hi ${f}! It's ${t}. Do you have a signature dish — something you're really good at making?`,
    (f, t) => `Hey ${f}! This is ${t}. Comfort food — what's yours, and what makes it so comforting?`,
    (f, t) => `Hello ${f}! I'm ${t}. Have you ever tried to recreate a restaurant dish at home? How did it go?`,
    (f, t) => `Hi ${f}, ${t} calling! What's your favorite cuisine from a different country — not Korean?`,
    (f, t) => `Hey ${f}! ${t} speaking. If you could only eat one meal for the rest of your life, what would it be?`,
    (f, t) => `Hello ${f}! This is ${t}. Do you think you're a picky eater, or do you eat pretty much anything?`,
    (f, t) => `Hi ${f}! I'm ${t}. What's a food memory from your childhood that really sticks with you?`,
    (f, t) => `Hey ${f}, ${t} here! Have you ever had a total cooking disaster? Tell me about it!`,
    (f, t) => `Hello ${f}! It's ${t}. What's a dish you've always wanted to learn to cook but haven't tried yet?`,
    (f, t) => `Hi ${f}! This is ${t}. Street food or fancy restaurant — which do you prefer and why?`,
    (f, t) => `Hey ${f}! I'm ${t}. What's something you eat that other people find unusual or surprising?`,
    (f, t) => `Hello ${f}, ${t} calling! When you're tired and hungry, what's your go-to easy meal?`,
    (f, t) => `Hi ${f}! ${t} here. Have you ever followed a recipe from another country and tried to make it at home?`,
    (f, t) => `Hey ${f}! This is ${t}. What do you think makes a truly great meal — is it the food, the company, the setting?`,
  ],

  "Movies & TV": [
    (f, t) => `Hey ${f}! It's ${t}. Have you watched anything good lately that you couldn't stop thinking about?`,
    (f, t) => `Hi ${f}, ${t} here! Are you more of a movie person or a TV series binge-watcher?`,
    (f, t) => `Hello ${f}! This is ${t}. What's your all-time favorite movie — the one you could watch again and again?`,
    (f, t) => `Hey ${f}! I'm ${t}. What genre do you always find yourself coming back to — thriller, comedy, romance?`,
    (f, t) => `Hi ${f}! ${t} speaking. Is there a show or movie you've been meaning to watch but keep putting off?`,
    (f, t) => `Hello ${f}, ${t} here! What's a film that genuinely surprised you — the ending or story went somewhere you didn't expect?`,
    (f, t) => `Hey ${f}! It's ${t}. Do you prefer watching things in English with subtitles, or dubbed in Korean?`,
    (f, t) => `Hi ${f}! This is ${t}. What's a Korean drama or movie you'd recommend to someone who's never seen Korean content?`,
    (f, t) => `Hello ${f}! I'm ${t}. Have you ever watched something that actually changed your perspective on life?`,
    (f, t) => `Hey ${f}, ${t} calling! If someone asked you to describe your taste in movies in three words, what would you say?`,
    (f, t) => `Hi ${f}! ${t} speaking. What was the last movie you watched in a cinema? Was it worth it?`,
    (f, t) => `Hello ${f}! This is ${t}. Do you have a favorite actor or director whose work you always follow?`,
    (f, t) => `Hey ${f}! I'm ${t}. What's the most overrated movie or show everyone loves that you just didn't get?`,
    (f, t) => `Hi ${f}, ${t} here! Is there a classic movie from before you were born that you love?`,
    (f, t) => `Hello ${f}! It's ${t}. What's a show or movie that made you cry — and are you willing to admit what it was?`,
    (f, t) => `Hey ${f}! This is ${t}. Do you think streaming has changed how you enjoy movies compared to going to the cinema?`,
    (f, t) => `Hi ${f}! I'm ${t}. What's a documentary or true story adaptation that really stuck with you?`,
    (f, t) => `Hello ${f}, ${t} speaking! If your life were made into a movie, what genre would it be?`,
    (f, t) => `Hey ${f}! It's ${t}. What show have you recommended to the most people and why?`,
    (f, t) => `Hi ${f}! This is ${t}. Is there a movie or TV character you feel like you really relate to?`,
  ],

  "Work & Career": [
    (f, t) => `Hello ${f}! It's ${t}. Tell me a little about what you do for work — what's a typical day like for you?`,
    (f, t) => `Hi ${f}, ${t} here! What do you enjoy most about your job right now?`,
    (f, t) => `Hey ${f}! This is ${t}. Is there a part of your career you wish you'd started sooner?`,
    (f, t) => `Hello ${f}! I'm ${t}. What made you choose the career path you're on now?`,
    (f, t) => `Hi ${f}! ${t} speaking. What's been the most challenging work situation you've faced recently?`,
    (f, t) => `Hey ${f}, ${t} calling! Do you work better alone or as part of a team — and what makes the difference for you?`,
    (f, t) => `Hello ${f}! This is ${t}. If you could switch careers tomorrow with no consequences, what would you do?`,
    (f, t) => `Hi ${f}! It's ${t}. What does success in your field look like to you personally?`,
    (f, t) => `Hey ${f}! I'm ${t}. Have you ever had a mentor who really made a difference in your career?`,
    (f, t) => `Hello ${f}, ${t} here! What skill do you think is most important in your line of work?`,
    (f, t) => `Hi ${f}! ${t} speaking. What's a work achievement you're genuinely proud of?`,
    (f, t) => `Hey ${f}! This is ${t}. How do you handle it when work gets really stressful or overwhelming?`,
    (f, t) => `Hello ${f}! I'm ${t}. What's something about your industry that people outside of it would find surprising?`,
    (f, t) => `Hi ${f}, ${t} calling! Do you think work-life balance is possible in your field — how do you manage it?`,
    (f, t) => `Hey ${f}! It's ${t}. What's one thing you wish your company or workplace did differently?`,
    (f, t) => `Hello ${f}! This is ${t}. Have you ever had a really difficult colleague or boss? How did you handle it?`,
    (f, t) => `Hi ${f}! I'm ${t}. What career advice would you give to someone just starting out in your field?`,
    (f, t) => `Hey ${f}, ${t} here! Are you where you thought you'd be in your career at this point — or did things take a different turn?`,
    (f, t) => `Hello ${f}! ${t} speaking. What's something new you've learned on the job recently?`,
    (f, t) => `Hi ${f}! This is ${t}. Where do you see your career heading in the next few years — any big goals or changes?`,
  ],
};

export function getRandomGreeting(topic: string, firstName: string, tutorName: string): string {
  const list = greetings[topic];
  if (!list || list.length === 0) {
    return `Hey ${firstName}! This is ${tutorName}, your English tutor. How are you doing today?`;
  }
  const fn = list[Math.floor(Math.random() * list.length)];
  return fn(firstName, tutorName);
}
